import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Reusable/NavBar";
import Footer from "@/components/Reusable/Footer";

export const metadata: Metadata = {
  title: "Hashmint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative overflow-x-hidden">
        <NavBar />
        {children}
        <Footer />
        {/* <Footer /> */}
      </body>
    </html>
  );
}
