import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Reusable/NavBar";
import Footer from "@/components/Reusable/Footer";



export const metadata: Metadata = {
  title: "Hashmint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

    <body >
      <NavBar />
      {children}
      {/* <SpeedInsights />  */}
      <Footer />
    </body>
  </html>
  );
}
