import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Reusable/NavBar";
import Footer from "@/components/Reusable/Footer";
import Hero from "@/components/Hero/HeroSection";



export const metadata: Metadata = {
  title: "Hashmint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD

    <body >
      <NavBar />
      {children}
      {/* <SpeedInsights />  */}
      <Footer />
    </body>
  </html>
=======
      <body>
        <NavBar />
        <Hero />
        {children}
        <Footer />
      </body>
    </html>
>>>>>>> 15e047c4a90b3d6f82400500e0a4b4d5a637bdcc
  );
}
